### ISSUE TITLE
RunQueryResponse in firestore API v1 holds a single document instead of a list

### ISSUE THREAD

**Issue by alextekartik** [google/googleapis.dart#101] opened 2020-05-26 17:56 UTC
I cannot manage to use the runQuery firestore API (v1).

The response is defined as a map holding a single document
```dart
/// The response for Firestore.RunQuery.
class RunQueryResponse {
  /// A query result.
  /// Not set when reporting partial progress.
  Document document;
  ...
}
```

although the JSON result look like an array:
```
 [
        {
          'document': {
            'createTime': '2018-10-27T05:34:53.459862Z',
            'fields': {...
```

So the decoder complains and calling runQuery simply failed.

Not easy to extract a running example although it is quite easy to reproduce running any query (even without any response). Since the API is generated maybe there is an error somewhere else in the source definition or the generator

**Comment by alextekartik** [comment] 2020-05-28 10:13
Looks like a dup of https://github.com/dart-lang/googleapis/issues/25 which has been closed.

Even the REST documentation is incorrect:
https://firebase.google.com/docs/firestore/reference/rest/v1/projects.databases.documents/runQuery

Unfortunately this make the firestore REST unusable...how can we report this to the firestore team (initial issue reported more than 2 years ago!)

**Comment by roughike** [comment] 2020-06-24 20:47
I'm running into the same issue. Essentially this prevents doing any kind of Firestore query altogether using the API.

The problem is in this discovery document: https://firestore.googleapis.com/$discovery/rest?version=v1 - the Rust wrapper seems to have the exact same issue: Byron/google-apis-rs#220. It might be the same for other languages and packages too.

@jonasfj I understand this is an issue in the Discovery Document - so it's _not this Dart package_ that has the bug. I also understand that _this should be fixed by the Firestore Team_. **But do you know how to reach them?** Or do you know anyone who knows how to reach them & report this bug?

In the meantime, I will try to fix the discovery document myself and if that works, depend on a fork until this is officially fixed.

**Comment by jonasfj** [comment] 2020-06-30 13:03
I have no more information.

Closed duplicate.

> In the meantime, I will try to fix the discovery document myself and if that works, depend on a fork until this is officially fixed.

This is a good solution, I would suggest publishing it as a separate package, maybe call it `package:firestore_rest_api`.
Ideally, you can also wrap the firebase REST API with some nicer wrappers, the generated APIs aren't that nice to begin with.

**Comment by anthoneyrimmer** [comment] 2021-06-15 03:57
Hi @jonasfj , did you end up resolving this? 
Hi @roughike , I just submitted a bug request via the Firebase support page, have you already done that?

**Comment by jonasfj** [comment] 2021-06-15 07:53
I have no solution for this. It's possible that we should simply update the code-generation scripts in this repository to know about this bug and make a workaround.

**Comment by alextekartik** [comment] 2021-06-15 09:34
I have created a single file with just a correction for this single call here:
https://github.com/tekartik/firebase_firestore.dart/blob/master/firestore_rest/lib/src/firestore/v1_fixed.dart

It can be copied and used the same way (i.e. use FirestoreFixedApi instead of FirestoreApi to call runQuery)

**Comment by jonasfj** [comment] 2021-06-15 10:59
@alextekartik we can do something like that, but it will probably need to be integrated with `dart generator/bin/generate.dart run_config generate`, so that such a patch is automatically applied.

Ideal would be a patch that is automatically applied to the discovery API document, after it's downloaded.

**Comment by kevmoo** [comment] 2021-06-15 20:07
It might be worth looking into a system for adding overrides. If the input data we get is "bad".

Reopening!

**Comment by anthoneyrimmer** [comment] 2021-06-22 22:10
I received this from the firebase support team, I will be looking for confirmation that they have actually found the work in progress. 

Thanks for the clarification. I have done some research about this issue, since it has been already reported in the link you shared, actually the engineering team is aware of this issue and they are currently working to fix it. However there's no telling when this will be completely fixed, but you can keep an eye on the Firebase Release Notes to be informed of the latest from Firebase.

**Closed** 2021-10-17 03:39 UTC
Labels: override-needed
