### ISSUE TITLE
List<dynamic> Map<String,dynamic> error

### ISSUE THREAD

**Issue by SercanKaya0** [google/googleapis.dart#334] opened 2021-10-16 21:37 UTC
admob network generate gives an error. The data comes as a list, but it is still not fixed in version 6.0.0, which was sent as a map.

  async.Future<GenerateNetworkReportResponse> generate(
    GenerateNetworkReportRequest request,
    core.String parent, {
    core.String? $fields,
  }) async {
    final _body = convert.json.encode(request);
    final _queryParams = <core.String, core.List<core.String>>{
      if ($fields != null) 'fields': [$fields],
    };

    final _url =
        'v1/' + core.Uri.encodeFull('$parent') + '/networkReport:generate';

    final _response = await _requester.request(
      _url,
      'POST',
      body: _body,
      queryParams: _queryParams,
    );
    
    // issue 
    return GenerateNetworkReportResponse.fromJson(
        _response as core.Map<core.String, core.dynamic>);
  }

**Comment by kevmoo** [comment] 2021-10-17 03:42
Duplicate of https://github.com/google/googleapis.dart/issues/183 – which I just reopend.

Sorry!

**Closed by kevmoo** 2021-10-17 03:42 UTC
Labels: override-needed, google-internal-issue-needed, package:googleapis
