### ISSUE TITLE
Unhandled Exception: type 'List<dynamic>' is not a subtype of type 'Map<String, dynamic>' in type cast

### ISSUE THREAD

**Issue by SercanKaya0** [google/googleapis.dart#299] opened 2021-09-22 08:53 UTC
Flutter google admob apis issue. 

[VERBOSE-2:ui_dart_state.cc(209)] Unhandled Exception: type 'List<dynamic>' is not a subtype of type 'Map<String, dynamic>' in type cast

**Comment by kevmoo** [comment] 2021-09-22 15:30
Please include the versions of flutter, the packages you're using, and the API call you made!

**Comment by SercanKaya0** [comment] 2021-09-22 15:34
Flutter : 2.5.1 
googleapis : 5.0.1 

 await _googleSignIn.signInSilently();
      final client = await _googleSignIn.authenticatedClient();
      if (client != null) {
        final AdMobApi admobApi = AdMobApi(client);

        GenerateNetworkReportResponse admobAdUnits =
            await admobApi.accounts.networkReport.generate(
                GenerateNetworkReportRequest(
                  reportSpec: (NetworkReportSpec(
                      dateRange:
                          DateRange(endDate: endDate, startDate: startDate),
                      metrics: [
                        "AD_REQUESTS",
                        "CLICKS",
                        "ESTIMATED_EARNINGS",
                        "IMPRESSIONS",
                        "IMPRESSION_CTR",
                        "IMPRESSION_RPM",
                        "MATCHED_REQUESTS",
                        "MATCH_RATE",
                        "SHOW_RATE"
                      ],
                      dimensions: [
                        "DATE",
                        // "MONTH",
                        // "WEEK",
                        "AD_UNIT",
                        "APP",
                        "COUNTRY",
                        "FORMAT",
                        "PLATFORM",
                        "MOBILE_OS_VERSION",
                        "GMA_SDK_VERSION",
                        "APP_VERSION_NAME",
                        "SERVING_RESTRICTION"
                      ],)),
                ),
                parent);

        return Result.success(admobAdUnits);

errorMessage type 'List<dynamic>' is not a subtype of type 'Map<String, dynamic>' in type cast

**Comment by kevmoo** [comment] 2021-09-22 15:36
Duplicate of https://github.com/google/googleapis.dart/issues/183 – but thanks for the repro!

**Closed by kevmoo** 2021-09-22 15:36 UTC

**Comment by SercanKaya0** [comment] 2021-09-22 15:37
Ok, I see but i dont fixed

**Comment by kevmoo** [comment] 2021-09-22 15:37
@SercanKaya0 – see the other issue. I need to dig to see if I can figure out a work-around.

**Comment by SercanKaya0** [comment] 2021-09-22 15:54
Hmm, Okey, I'm waiting for your good news. :)
