### ISSUE TITLE
Issue in JSON def for runQuery method; it should return a list of RunQueryResponse objects

### ISSUE THREAD

**Issue by brenhr** [google/googleapis.dart#303] opened 2021-09-29 22:40 UTC
If you make a request to the runQuery method: https://firestore.googleapis.com/v1beta1/{parent=projects/*/databases/*/documents}:runQuery, you will get a list of RunQueryResponse, but the JSON file says it returns a  single RunQueryResponse object.
When we generate the code from the JSON, we get parsing errors.

The error seems to be here: 
https://github.com/google/googleapis.dart/blob/914cf010bdf2a45201f06ff0657a29042634f4ed/discovery/googleapis/firestore__v1.json#L2618
the type should be "array" instead of "object".

Google-internal issue: http://b/38230466

**Comment by kevmoo** [comment] 2021-09-29 22:48
Why is there a `v1beta1` section in the URL above? Are you using the v1 API?

Would you include an example of the JSON being returned?

It's possible the JSON we're getting from the discovery API is broken

**Comment by kevmoo** [comment] 2021-09-29 23:43
Don't close it! It's a good bug! I just reproduced it!

**Comment by kevmoo** [comment] 2021-09-29 23:53
This goes back a ways!  https://github.com/google/googleapis.dart/issues/25

**Comment by kevmoo** [comment] 2021-09-30 00:53
Good find @brenhr ! Fix will be in the next release!

**Comment by kevmoo** [comment] 2021-10-13 00:28
Fix published in https://pub.dev/packages/googleapis/versions/6.0.0

**Comment by alextekartik** [comment] 2022-06-05 09:18
It seems that the fix has disappear (unless I'm wrong). The RunQueryResponse definition has changed as it was before in 9.0.0 version

**Comment by kevmoo** [comment] 2022-06-06 04:19
Will look!

**Comment by kevmoo** [comment] 2022-06-07 19:01
I can't get a query to run – at all.

Could you share an example of a query that runs – but just the result fails to decode. Or are you getting failures with invalid queries?

**Comment by alextekartik** [comment] 2022-06-07 20:08
Indeed it seems the request API has changed too. The following example ran on googleapis 8.1.0:

```dart
import 'package:googleapis/firestore/v1.dart';
import 'package:http/http.dart';
import 'package:path/path.dart' as p;
import 'package:test/test.dart';

void main() {
  test('runQuery', () async {
    var client = Client();
    try {
      // Temp no auth query
      var path =
          'projects/tekartik-net-dev/databases/(default)/documents/tests/tekartik_firebase/tests/a2OZAEskPoMDERpjLEc4/et1fJO9Bk8iGu9MaMpXh';
      var firestoreApi = FirestoreApi(client);
      // Run query
      var query = RunQueryRequest()
        ..structuredQuery = StructuredQuery(
            from: [CollectionSelector()..collectionId = p.url.basename(path)]);
      var response = await firestoreApi.projects.databases.documents
          .runQuery(query, p.url.dirname(path));
      // There should be 2 documents
      print(response.map((element) => element.document?.toJson()).join('\n'));
    } finally {
      client.close();
    }
  });
}
```

but not on googleapis 9.0.0 (does not even compile).

The following compiles on googleapis 9.0.0 but crashes due to invalid json (i.e. a list instead of a map)

```dart
import 'package:googleapis/firestore/v1.dart';
import 'package:http/http.dart';
import 'package:path/path.dart' as p;
import 'package:test/test.dart';

void main() {
  test('runQuery', () async {
    var client = Client();
    try {
      // Temp no auth query
      var path =
          'projects/tekartik-net-dev/databases/(default)/documents/tests/tekartik_firebase/tests/a2OZAEskPoMDERpjLEc4/et1fJO9Bk8iGu9MaMpXh';
      var firestoreApi = FirestoreApi(client);
      // Run query
      var query = RunQueryRequest()
        ..add(RunQueryRequestElement()
          ..structuredQuery = StructuredQuery(from: [
            CollectionSelector()..collectionId = p.url.basename(path)
          ]));
      // Crashes!
      // DetailedApiRequestError(status: 400, message: Invalid JSON payload received. Unknown name "": Root element must be a message.)
      var response = await firestoreApi.projects.databases.documents
          .runQuery(query, p.url.dirname(path));
      print(response.toJson());

    } finally {
      client.close();
    }
  });
}
```

**Comment by kevmoo** [comment] 2022-06-07 20:44
I'm trying to reproduce, but I can't get beyond an error

```
DetailedApiRequestError(status: 400, message: Invalid JSON payload received. Unknown name "": Root element must be a message.)
```

Any ideas @alextekartik ?

**Comment by alextekartik** [comment] 2022-06-07 20:53
Yes, the response is an array (a list of doc). The patch that was made here (https://github.com/google/googleapis.dart/blob/master/overrides/i303.diff) fixed that. Maybe the fetched definition has slightly changed and the patch is not applied correctly. (and maybe the patch must be updated to match any api changes).

Looking quickly at the patch, it seems that the RunQueryRequest is patched and RunQueryResponse was patched before (https://github.com/google/googleapis.dart/blob/d115d930eb6768bf213d157e4132c950f30ed26c/overrides/i303.diff). The change made 15 days seems to have broken that (https://github.com/google/googleapis.dart/commit/1fc8bb479d28fed1ad0ae3ea46af7594bced3d86#diff-ca3f7c28ab7c8e8fb2729ea13ddebcc369850061660de53c8523d7c333a403c7)

**Comment by kevmoo** [comment] 2022-06-07 20:54
@alextekartik – possible user error (on my part). Will experiment more!

**Comment by kevmoo** [comment] 2022-06-08 00:08
I'm going nuts trying to get any queries working here, @alextekartik 

My idea: I'll do a cleanup PR to undo my mistake. I'll tag you and you can verify I've fixed it w/ your use case...then I can publish.

Fair @alextekartik ?

**Comment by alextekartik** [comment] 2022-06-08 05:53
Sure @kevmoo I can verify.

If you have a way to add some adhoc testing in the whole code generation, the following stupid unit test work on 8.1.0 but does not even compile n 9.0.0:

```dart
import 'package:googleapis/firestore/v1.dart';
import 'package:test/test.dart';

void main() {
  test('RunQueryResponse patch', () async {
    // The patched response is a list, not a single object as defined in the original definition
    expect(RunQueryResponse.fromJson([]), isEmpty);
  });
}
```

**Comment by kevmoo** [comment] 2022-06-08 18:33
Check out #419 @alextekartik

**Comment by alextekartik** [comment] 2022-06-08 20:11
I have tried my various tests with the following dependency overrides:

```yaml
  googleapis:
    git:
      url: https://github.com/google/googleapis.dart
      path: generated/googleapis
      ref: i303
```

Everything looks ok for me! Thanks.

**Closed** 2022-06-08 20:33 UTC
Labels: bug, override-needed

**Comment by alextekartik** [comment] 2022-06-08 22:54
Thanks for your fast fix. v9.1.0 published makes my CI happy again: https://github.com/tekartik/firebase_firestore.dart/actions/runs/2464591115

**Comment by kevmoo** [comment] 2022-06-09 00:14
👍👍👍
