### ISSUE TITLE
[Calendar] Unable to use clientViaUserConsent it gives me Authorization Error

### ISSUE THREAD

**Issue by dhavalagile** [google/googleapis.dart#402] opened 2022-04-29 17:41 UTC
I had double-checked my ClientId for both platforms but still face issues for getting AuthClient for create a calendar event.

`  static final androidClientId = ClientId('xxxxxxxx.apps.googleusercontent.com');
  static final iOSClientId = ClientId('xxxxxxx.apps.googleusercontent.com');

final _clientID = Platform.isAndroid ? EventProvider.androidClientId : EventProvider.iOSClientId;
    final _scopes = [CalendarApi.calendarScope];
    clientViaUserConsent(_clientID, _scopes, prompt).then((AuthClient client) {
}
void prompt(String url) async {
     print("  => $url");
     if (await canLaunch(url)) {
       await launch(URL);
     } else {
       throw 'Could not launch $url';
     }
    }
`

I am referring to this article for creating an event in google calendar.
- https://blog.codemagic.io/google-meet-events-in-flutter/
- https://medium.com/flutter-community/flutter-use-google-calendar-api-adding-the-events-to-calendar-3d8fcb008493

![Simulator Screen Shot - iPhone 13 - 2022-04-29 at 23 10 46](https://user-images.githubusercontent.com/25456773/165995583-a1b239af-4b8b-4ee6-a4ee-410c81e433a3.png)

**Comment by enesoruc96** [comment] 2022-05-03 18:52
i am having the same problem.

**Comment by SungHyun22** [comment] 2022-05-17 07:31
i have same problem here,,,

**Comment by Aanu1995** [comment] 2022-05-17 18:25
Any solution to this?

**Comment by kevmoo** [comment] 2022-05-25 21:59
I'm closing out as a duplicate of https://github.com/google/googleapis.dart/issues/390 – please subscribe to that issue for updates!

**Closed by kevmoo** 2022-05-25 21:59 UTC

**Comment by dhavalagile** [comment] 2022-05-26 04:36
@kevmoo, Why you are close to this issue still #390 doesn't have any solution?

**Comment by kevmoo** [comment] 2022-05-26 06:08
No answer yet on this. Just wanted to consolidate the threads!
